### PR TITLE
updated the redme.md.

### PR DESCRIPTION
**Pull request by nagarathnamma**
updated the redme.md for latest operator sdk version

### CODE REVIEW

**Comment by GergoBota** [comment]
@howardhalili for some reason i cant merge, are you able? ( the readme will anyway be changed by denes now that we have the generation, so just a small change in the meantime

**Comment by howardhalili** [comment]
@GergoBota no, can't see the merge button. how about @hochdorf ?

**Comment by howardhalili** [comment]
@GergoBota 
image
needs to be approved, i can't approve it. @hochdorf can you?

**Comment by hochdorf** [comment]
yes, approved

**Comment by howardhalili** [comment]
@GergoBota somehow i still can't see the merge button, so i can't merge.

**Review by GergoBota — APPROVED** [review]

**Comment by GergoBota** [comment]
@howardhalili can you check if any change here.. would be good to close/merge this @nagarathnamma

**Comment by howardhalili** [comment]
i haven't regained my merge rights.

**Comment by howardhalili** [comment]
@hochdorf i think we can merge this. i haven't regain my merge rights. thanks!

**Pull request merged**
